### PR TITLE
Support autoincrement clause for sqlite

### LINKED ISSUE #234: AUTOINCREMENT syntax for sqlite is not supported
In sqlite the syntax for auto increment is as follows:

```sql
CREATE TABLE example_table (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    -- other columns
);
```

This is not supported by the parser as it throws the following error:

`mo_parsing.exceptions.ParseException: Expecting {auto_increment} | {rb}, found "AUTOINCREM" (at char 57), (line:2, col:35)`

### PR DESCRIPTION
**Pull request by megh-khaire**
Fixes #234

### CODE REVIEW

**Comment by klahnakoski** [comment]
Thank you for this!  Please revert the whitespace changes on the readme, and add a test.  

I will look at this more on the weekend.

**Comment by megh-khaire** [comment]
> Thank you for this! Please revert the whitespace changes on the readme, and add a test.
> 
> I will look at this more on the weekend.

Done!
Thank you for looking into it :)
Love the library

**Comment by klahnakoski** [comment]
I am having problems with my CI pipeline.  Trying to fix it tonight.

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-sql-parsing/10.627.24135/

**Comment by megh-khaire** [comment]
Thank you!

**Pull request merged**
